import type { Metadata } from "next";
import { Inter, Poppins, Cormorant } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
  variable: '--font-default',
});
const cormorant = Cormorant({
  subsets: ["latin"],
  weight: ["400"],
  variable: '--font-cor',
});
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${cormorant.variable}`}>{children}</body>
    </html>
  );
}
